buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'
    }
}

plugins {
    id 'com.android.application'
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

android {
    namespace 'com.axror.bazarcontrol'
    compileSdk 33

    defaultConfig {
        applicationId "com.axror.bazarcontrol"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
