plugins {
    id 'com.android.application'
}
android {
    namespace 'com.axror.bazarcontrol'
    compileSdk 33
    defaultConfig {
        applicationId "com.axror.bazarcontrol"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
